export const SCREENS_PATH = '/screens/';

export const SCREEN_DEVICES = ['iphone', 'ipad', 'mac', 'watch'] as const;
export const SCREEN_TYPES = [
  'home',
  'onboarding',
  'paywall',
  'empty',
  'settings',
  'detail',
  'stats',
  'compose',
  'list',
  'camera',
  'player',
  'widget',
] as const;
export const APP_CATEGORIES = [
  'productivity',
  'finance',
  'travel',
  'health',
  'photo',
  'social',
  'weather',
  'developer',
  'entertainment',
  'reference',
  'utilities',
] as const;
export const MRR_BANDS = ['under-10k', '10k-50k', '50k-100k', '100k-plus'] as const;
export const SPOTLIGHTS = ['indie', 'breakout', 'studio'] as const;

export type ScreenDevice = (typeof SCREEN_DEVICES)[number];
export type ScreenType = (typeof SCREEN_TYPES)[number];
export type AppCategory = (typeof APP_CATEGORIES)[number];
export type MrrBand = (typeof MRR_BANDS)[number];
export type Spotlight = (typeof SPOTLIGHTS)[number];
export type Chrome = 'light' | 'dark';

export type ScreenEntry = {
  slug: string;
  app: string;
  title: string;
  description: string;
  why: string;
  device: ScreenDevice;
  screenType: ScreenType;
  category: AppCategory;
  mrr: MrrBand;
  spotlight: Spotlight;
  art: string;
  chrome: Chrome;
  featured?: boolean;
  appUrl?: string;
  image?: string;
  imageAlt?: string;
};

export const DEVICE_LABELS: Record<ScreenDevice, string> = {
  iphone: 'iPhone',
  ipad: 'iPad',
  mac: 'Mac',
  watch: 'Watch',
};

export const SCREEN_TYPE_LABELS: Record<ScreenType, string> = {
  home: 'Home',
  onboarding: 'Onboarding',
  paywall: 'Paywall',
  empty: 'Empty state',
  settings: 'Settings',
  detail: 'Detail',
  stats: 'Stats',
  compose: 'Compose',
  list: 'List',
  camera: 'Camera',
  player: 'Now playing',
  widget: 'Widget',
};

export const CATEGORY_LABELS: Record<AppCategory, string> = {
  productivity: 'Productivity',
  finance: 'Finance',
  travel: 'Travel',
  health: 'Health & Fitness',
  photo: 'Photo & Video',
  social: 'Social',
  weather: 'Weather',
  developer: 'Developer',
  entertainment: 'Entertainment',
  reference: 'Reference',
  utilities: 'Utilities',
};

export const MRR_LABELS: Record<MrrBand, string> = {
  'under-10k': '<$10k',
  '10k-50k': '$10–50k',
  '50k-100k': '$50–100k',
  '100k-plus': '$100k+',
};

export const SPOTLIGHT_LABELS: Record<Spotlight, string> = {
  indie: 'Indie',
  breakout: 'Breakout',
  studio: 'Studio',
};

export const SCREENS_DESCRIPTION =
  'A reference of original app screen reconstructions from breakout hits and lesser-known indie apps. Filter by device, category, MRR band, and screen type.';

export const SCREENS: ScreenEntry[] = [
  {
    slug: 'flighty-live-board',
    app: 'Flighty',
    title: 'Live flight board',
    description: 'A single live card that turns a boarding pass into a status object you can glance at.',
    why: 'The home screen is one job: is my flight okay? Gate, delay, and countdown sit on one surface instead of a dashboard of widgets. Indie travel apps often over-explain; Flighty trusts the next action.',
    device: 'iphone',
    screenType: 'home',
    category: 'travel',
    mrr: '100k-plus',
    spotlight: 'breakout',
    art: 'flighty-home',
    chrome: 'dark',
    featured: true,
    appUrl: 'https://apps.apple.com/app/id1358823008',
  },
  {
    slug: 'flighty-onboarding',
    app: 'Flighty',
    title: 'Calendar import onboarding',
    description: 'Permission with a payoff: import trips, then prove the product in one screen.',
    why: 'Onboarding asks for calendar access only after showing what you get. The illustration is the feature, not a mascot. That sequencing is why travel apps convert permission grants.',
    device: 'iphone',
    screenType: 'onboarding',
    category: 'travel',
    mrr: '100k-plus',
    spotlight: 'breakout',
    art: 'flighty-onboarding',
    chrome: 'dark',
    appUrl: 'https://apps.apple.com/app/id1358823008',
  },
  {
    slug: 'copilot-spend-home',
    app: 'Copilot Money',
    title: 'Spend home',
    description: 'Net worth and this month’s burn in a layout that feels like a magazine, not a bank.',
    why: 'Finance apps usually lead with accounts. Copilot leads with a feeling of control: one number, a sparkline, then categories. Hierarchy does the advising.',
    device: 'iphone',
    screenType: 'stats',
    category: 'finance',
    mrr: '100k-plus',
    spotlight: 'breakout',
    art: 'copilot-home',
    chrome: 'light',
    featured: true,
    appUrl: 'https://apps.apple.com/app/id1447330651',
  },
  {
    slug: 'copilot-paywall',
    app: 'Copilot Money',
    title: 'Annual paywall',
    description: 'A quiet paywall that sells the habit, not a grid of feature bullets.',
    why: 'One recommended plan, a yearly save callout, and social proof above the fold. The rest of the features wait. Most indie paywalls invert this and lose the tap.',
    device: 'iphone',
    screenType: 'paywall',
    category: 'finance',
    mrr: '100k-plus',
    spotlight: 'breakout',
    art: 'copilot-paywall',
    chrome: 'light',
    featured: true,
    appUrl: 'https://apps.apple.com/app/id1447330651',
  },
  {
    slug: 'things-today',
    app: 'Things 3',
    title: 'Today list',
    description: 'Headings, not projects, as the primary way to see a day.',
    why: 'Cultured Code treats Today like a newspaper. Sections create rhythm so a long list never feels like a dump. The empty rows are as considered as the filled ones.',
    device: 'iphone',
    screenType: 'list',
    category: 'productivity',
    mrr: '100k-plus',
    spotlight: 'studio',
    art: 'things-today',
    chrome: 'light',
    featured: true,
    appUrl: 'https://apps.apple.com/app/id904280700',
  },
  {
    slug: 'structured-day',
    app: 'Structured',
    title: 'Day timeline',
    description: 'A calendar that looks like a to-do list and a to-do list that looks like a day.',
    why: 'The timeline is the product. Time is vertical, tasks are blocks, and the current hour is a living cursor. It teaches timeboxing without a tutorial.',
    device: 'iphone',
    screenType: 'home',
    category: 'productivity',
    mrr: '50k-100k',
    spotlight: 'breakout',
    art: 'structured-day',
    chrome: 'light',
    appUrl: 'https://apps.apple.com/app/id1499198946',
  },
  {
    slug: 'ivory-timeline',
    app: 'Ivory',
    title: 'Home timeline',
    description: 'A Mastodon client that still feels like Tapbots: density with manners.',
    why: 'Avatars, names, and meta sit on a strict grid so posts can be long without becoming noisy. Boosts are visually quieter than originals — a small hierarchy most social clients skip.',
    device: 'iphone',
    screenType: 'list',
    category: 'social',
    mrr: '10k-50k',
    spotlight: 'studio',
    art: 'ivory-timeline',
    chrome: 'dark',
    appUrl: 'https://apps.apple.com/app/id6444602274',
  },
  {
    slug: 'ivory-settings',
    app: 'Ivory',
    title: 'Composer settings',
    description: 'Power-user toggles grouped like a hardware manual.',
    why: 'Settings are grouped by verb, not by API. You scan “When posting” instead of hunting feature flags. Indie apps often ship a flat table; this one reads as a product.',
    device: 'iphone',
    screenType: 'settings',
    category: 'social',
    mrr: '10k-50k',
    spotlight: 'studio',
    art: 'ivory-settings',
    chrome: 'dark',
    appUrl: 'https://apps.apple.com/app/id6444602274',
  },
  {
    slug: 'carrot-home',
    app: 'CARROT Weather',
    title: 'Snarky weather home',
    description: 'Forecast as a character, with the actual data still winning the layout.',
    why: 'Personality is a headline, not the whole screen. Temperature, precipitation, and hourly chips stay scannable. The joke never hides the number you opened the app for.',
    device: 'iphone',
    screenType: 'home',
    category: 'weather',
    mrr: '10k-50k',
    spotlight: 'indie',
    art: 'carrot-home',
    chrome: 'dark',
    featured: true,
    appUrl: 'https://apps.apple.com/app/id961390574',
  },
  {
    slug: 'halide-viewfinder',
    app: 'Halide',
    title: 'Manual viewfinder',
    description: 'Camera chrome that treats the sensor as a tool, not a filter pack.',
    why: 'Histogram, level, and format live on the edges so the preview stays sacred. Pro controls appear as ticks, not menus. That’s how a camera app earns trust from photographers.',
    device: 'iphone',
    screenType: 'camera',
    category: 'photo',
    mrr: '50k-100k',
    spotlight: 'studio',
    art: 'halide-camera',
    chrome: 'dark',
    appUrl: 'https://apps.apple.com/app/id885697368',
  },
  {
    slug: 'drafts-capture',
    app: 'Drafts',
    title: 'Capture editor',
    description: 'Opens on a keyboard. The rest of the app is downstream of that bet.',
    why: 'Most notes apps open on a library. Drafts opens on a blank page because the job is capture. Actions hide until you have text. That single decision is the whole product.',
    device: 'iphone',
    screenType: 'compose',
    category: 'productivity',
    mrr: '10k-50k',
    spotlight: 'studio',
    art: 'drafts-capture',
    chrome: 'light',
    appUrl: 'https://apps.apple.com/app/id1236254471',
  },
  {
    slug: 'sofa-queue',
    app: 'Sofa',
    title: 'Watch later queue',
    description: 'A media inbox with poster art, not a social feed pretending to be a list.',
    why: 'Sofa is a queue, so every row is something you intend to finish. Metadata is secondary to artwork and title. Unknown apps often copy Netflix; this copies a reading list.',
    device: 'iphone',
    screenType: 'list',
    category: 'entertainment',
    mrr: 'under-10k',
    spotlight: 'indie',
    art: 'sofa-queue',
    chrome: 'dark',
    featured: true,
    appUrl: 'https://apps.apple.com/app/id1276554886',
  },
  {
    slug: 'sofa-empty',
    app: 'Sofa',
    title: 'Empty library',
    description: 'An empty state with a next step and a personality, not a grey illustration.',
    why: 'Empty states fail when they only say “nothing here.” Sofa tells you what the app becomes after the first add, and puts the add button in the same optical center as future posters.',
    device: 'iphone',
    screenType: 'empty',
    category: 'entertainment',
    mrr: 'under-10k',
    spotlight: 'indie',
    art: 'sofa-empty',
    chrome: 'dark',
    appUrl: 'https://apps.apple.com/app/id1276554886',
  },
  {
    slug: 'parcel-tracking',
    app: 'Parcel',
    title: 'Package list',
    description: 'Tracking events as a timeline of cards you can scan in a grocery line.',
    why: 'Carrier jargon is rewritten as human states: ordered, moving, out for delivery. Color is reserved for exceptions. Utility apps win on glanceability, not on maps.',
    device: 'iphone',
    screenType: 'list',
    category: 'utilities',
    mrr: '10k-50k',
    spotlight: 'indie',
    art: 'parcel-list',
    chrome: 'light',
    appUrl: 'https://apps.apple.com/app/id375589283',
  },
  {
    slug: 'launchbuddy-reviews',
    app: 'LaunchBuddy',
    title: 'Customer reviews inbox',
    description: 'App Store reviews as a working inbox, with reply state visible before you open a thread.',
    why: 'ASC hides reply status in a web table. This screen makes replied vs open a first-class row attribute, which is the difference between a dashboard and a queue.',
    device: 'mac',
    screenType: 'list',
    category: 'developer',
    mrr: 'under-10k',
    spotlight: 'indie',
    art: 'photo',
    chrome: 'dark',
    image: '/screenshots/launchbuddy/customer-reviews.jpg',
    imageAlt: 'LaunchBuddy Customer Reviews inbox with ratings, locales, and replied status',
    appUrl: 'https://apps.apple.com/app/id1615169630',
  },
  {
    slug: 'launchbuddy-ai',
    app: 'LaunchBuddy',
    title: 'AI playbooks',
    description: 'Approval-gated AI actions sitting next to the release work they might change.',
    why: 'The screen is not a chat toy. Playbooks are listed as jobs with a human gate. That framing is how you put AI next to App Store Connect without giving it the keys.',
    device: 'mac',
    screenType: 'home',
    category: 'developer',
    mrr: 'under-10k',
    spotlight: 'indie',
    art: 'photo',
    chrome: 'dark',
    featured: true,
    image: '/screenshots/launchbuddy/ai.jpg',
    imageAlt: 'LaunchBuddy AI home with approval-gated playbooks for releases, reviews, and analytics',
    appUrl: 'https://apps.apple.com/app/id1615169630',
  },
  {
    slug: 'launchbuddy-releases',
    app: 'LaunchBuddy',
    title: 'Release board',
    description: 'Version, tasks, and changelog as one Kanban instead of three Apple pages.',
    why: 'Release work is a board because the state is the work. Metadata lives in the header so the cards can stay verbs. Developer tools should look like the job, not like a settings app.',
    device: 'mac',
    screenType: 'list',
    category: 'developer',
    mrr: 'under-10k',
    spotlight: 'indie',
    art: 'photo',
    chrome: 'dark',
    image: '/screenshots/launchbuddy/releases.jpg',
    imageAlt: 'LaunchBuddy Releases board with backlog tasks, version metadata, and changelog draft',
    appUrl: 'https://apps.apple.com/app/id1615169630',
  },
  {
    slug: 'timery-timer',
    app: 'Timery',
    title: 'One-tap timer',
    description: 'Toggl tracking reduced to big project targets and a running clock.',
    why: 'A tracker that takes three taps is a journal, not a timer. Timery puts recent projects on a grid your thumb already knows. Unknown utilities often win by removing chrome, not adding charts.',
    device: 'iphone',
    screenType: 'home',
    category: 'productivity',
    mrr: 'under-10k',
    spotlight: 'indie',
    art: 'timery-home',
    chrome: 'dark',
    appUrl: 'https://apps.apple.com/app/id1425368544',
  },
  {
    slug: 'foodnoms-log',
    app: 'Foodnoms',
    title: 'Meal log',
    description: 'Calories as a narrative of meals, not a spreadsheet of macros.',
    why: 'Logging is the hard part, so the screen is a plus button and a recap. Charts wait on another tab. Health apps that lead with graphs leak users at the first meal.',
    device: 'iphone',
    screenType: 'compose',
    category: 'health',
    mrr: '10k-50k',
    spotlight: 'indie',
    art: 'foodnoms-log',
    chrome: 'light',
    appUrl: 'https://apps.apple.com/app/id1479461686',
  },
  {
    slug: 'gentler-streak',
    app: 'Gentler Streak',
    title: 'Recovery home',
    description: 'Activity rings rewritten as permission to rest.',
    why: 'The hero number is readiness, not calories. Copy talks like a coach. That’s a product stance: most fitness homes shame you; this one negotiates.',
    device: 'iphone',
    screenType: 'stats',
    category: 'health',
    mrr: 'under-10k',
    spotlight: 'indie',
    art: 'gentler-home',
    chrome: 'light',
    featured: true,
    appUrl: 'https://apps.apple.com/app/id1576857102',
  },
  {
    slug: 'lookup-word',
    app: 'LookUp',
    title: 'Word of the day',
    description: 'A dictionary that opens like a poster, then becomes a definition.',
    why: 'Reference apps are usually search boxes. LookUp leads with a word worth keeping, then etymology as supporting type. Delight is the retention loop.',
    device: 'iphone',
    screenType: 'detail',
    category: 'reference',
    mrr: 'under-10k',
    spotlight: 'indie',
    art: 'lookup-word',
    chrome: 'light',
    appUrl: 'https://apps.apple.com/app/id872564448',
  },
  {
    slug: 'photomator-edit',
    app: 'Photomator',
    title: 'ML edit canvas',
    description: 'iPad photo editing with tools docked like a darkroom bench.',
    why: 'The image is 80% of the screen. Adjustments are a rail, not a stack of sliders covering the work. Pixelmator’s craft shows in the empty space.',
    device: 'ipad',
    screenType: 'detail',
    category: 'photo',
    mrr: '50k-100k',
    spotlight: 'studio',
    art: 'photomator-edit',
    chrome: 'dark',
    appUrl: 'https://apps.apple.com/app/id1444636541',
  },
  {
    slug: 'streaks-home',
    app: 'Streaks',
    title: 'Twelve habits',
    description: 'A home screen that is the widget: twelve circles, no inbox.',
    why: 'Streaks has almost no navigation because the task is binary. Completing a habit is a tap on a circle, which is why it survives as a Watch app too.',
    device: 'iphone',
    screenType: 'home',
    category: 'health',
    mrr: '10k-50k',
    spotlight: 'studio',
    art: 'streaks-home',
    chrome: 'dark',
    appUrl: 'https://apps.apple.com/app/id963034692',
  },
  {
    slug: 'overcast-player',
    app: 'Overcast',
    title: 'Now playing',
    description: 'A podcast player that still looks like 2015 in the best way: big type, one knob.',
    why: 'Artwork, title, and a single progress control. Effects are tucked away. Indie audio apps often decorate; Overcast remains a listening surface.',
    device: 'iphone',
    screenType: 'player',
    category: 'entertainment',
    mrr: '10k-50k',
    spotlight: 'indie',
    art: 'overcast-player',
    chrome: 'dark',
    appUrl: 'https://apps.apple.com/app/id888422857',
  },
  {
    slug: 'bear-note',
    app: 'Bear',
    title: 'Markdown note',
    description: 'Writing with a red accent and almost no chrome.',
    why: 'Typography is the UI. Tags live as inline tokens so the editor never becomes a file browser. That’s how a notes app stays calm after 2,000 notes.',
    device: 'iphone',
    screenType: 'detail',
    category: 'productivity',
    mrr: '50k-100k',
    spotlight: 'studio',
    art: 'bear-note',
    chrome: 'light',
    appUrl: 'https://apps.apple.com/app/id1016366447',
  },
  {
    slug: 'widgetsmith-gallery',
    app: 'Widgetsmith',
    title: 'Widget gallery',
    description: 'A grid of custom widgets that sells the product by looking like a Home Screen.',
    why: 'The gallery is a catalog of outcomes, not a settings form. People buy what they can already see on the wallpaper behind the chrome.',
    device: 'iphone',
    screenType: 'widget',
    category: 'utilities',
    mrr: '100k-plus',
    spotlight: 'breakout',
    art: 'widgetsmith-gallery',
    chrome: 'dark',
    appUrl: 'https://apps.apple.com/app/id1523682319',
  },
  {
    slug: 'stoic-checkin',
    app: 'Stoic',
    title: 'Daily check-in',
    description: 'Journaling as a short sequence of prompts, not a blank page dare.',
    why: 'Mood first, then one question. The keyboard arrives after a decision, which is why check-ins actually happen. Blank journals are where streaks die.',
    device: 'iphone',
    screenType: 'compose',
    category: 'health',
    mrr: '10k-50k',
    spotlight: 'indie',
    art: 'stoic-checkin',
    chrome: 'light',
    appUrl: 'https://apps.apple.com/app/id1312926037',
  },
  {
    slug: 'tripsy-itinerary',
    app: 'Tripsy',
    title: 'Trip itinerary',
    description: 'A trip as a day-by-day stack instead of a folder of confirmations.',
    why: 'Travel apps drown in PDFs. Tripsy extracts the next event and the map snippet. Unknown trip planners win when they feel like a concierge, not a file manager.',
    device: 'iphone',
    screenType: 'detail',
    category: 'travel',
    mrr: 'under-10k',
    spotlight: 'indie',
    art: 'tripsy-trip',
    chrome: 'light',
    appUrl: 'https://apps.apple.com/app/id1429967544',
  },
  {
    slug: 'play-library',
    app: 'Play',
    title: 'Saved videos',
    description: 'Watch later for the open web, with source and duration as first-class labels.',
    why: 'Safari reading lists fail for video. Play looks like a media library: thumbnail, length, origin. The screen teaches you what the app is in one glance.',
    device: 'iphone',
    screenType: 'list',
    category: 'entertainment',
    mrr: '10k-50k',
    spotlight: 'indie',
    art: 'play-library',
    chrome: 'dark',
    appUrl: 'https://apps.apple.com/app/id1596506190',
  },
  {
    slug: 'darkroom-edit',
    app: 'Darkroom',
    title: 'Curve editor',
    description: 'Photo editing with curves as the hero control, not a buried advanced pane.',
    why: 'Darkroom assumes you came to grade. The curve is huge; presets are a strip. Pro tools that hide behind “more” never become muscle memory.',
    device: 'iphone',
    screenType: 'detail',
    category: 'photo',
    mrr: '50k-100k',
    spotlight: 'studio',
    art: 'darkroom-edit',
    chrome: 'dark',
    appUrl: 'https://apps.apple.com/app/id953286746',
  },
  {
    slug: 'paku-radar',
    app: 'Paku',
    title: 'Rain radar',
    description: 'A weather radar that looks like a vinyl widget: one place, one loop.',
    why: 'Paku is tiny on purpose. Location, temperature, and a looping radar. Unknown weather apps often clone Dark Sky’s density; this one clones a watch face.',
    device: 'iphone',
    screenType: 'home',
    category: 'weather',
    mrr: 'under-10k',
    spotlight: 'indie',
    art: 'paku-radar',
    chrome: 'dark',
    featured: true,
    appUrl: 'https://apps.apple.com/app/id1582559014',
  },
  {
    slug: 'dato-menu-bar',
    app: 'Dato',
    title: 'Menu bar calendar',
    description: 'A Mac utility that treats the clock as a popover full of the next events.',
    why: 'The product is the click on the time. No dock icon required. Menu bar apps live or die on that first popover — Dato fills it with calendar, world clocks, and nothing cute.',
    device: 'mac',
    screenType: 'widget',
    category: 'utilities',
    mrr: 'under-10k',
    spotlight: 'indie',
    art: 'dato-menu',
    chrome: 'dark',
    appUrl: 'https://apps.apple.com/app/id1470584107',
  },
  {
    slug: 'flighty-watch',
    app: 'Flighty',
    title: 'Next flight watch',
    description: 'Gate and countdown on a Watch face complication-scale surface.',
    why: 'If the iPhone screen is a briefing, the Watch is a glance. Two numbers, one color for status. Live Activities started here: reduce until it still means something.',
    device: 'watch',
    screenType: 'widget',
    category: 'travel',
    mrr: '100k-plus',
    spotlight: 'breakout',
    art: 'flighty-watch',
    chrome: 'dark',
    appUrl: 'https://apps.apple.com/app/id1358823008',
  },
  {
    slug: 'macrofactor-trend',
    app: 'MacroFactor',
    title: 'Weight trend',
    description: 'A nutrition app that leads with the algorithm’s trend line, not yesterday’s calories.',
    why: 'MacroFactor sells trust in an estimate. The screen shows the trend, the scale noise, and the next target together so logging feels like feeding a model, not dieting.',
    device: 'iphone',
    screenType: 'stats',
    category: 'health',
    mrr: '100k-plus',
    spotlight: 'breakout',
    art: 'macrofactor-trend',
    chrome: 'dark',
    appUrl: 'https://apps.apple.com/app/id1552561676',
  },
];

export const SCREENS_FAQ = [
  {
    question: 'Are these official screenshots?',
    answer:
      'No. Most entries are original reconstructions of well-known screen patterns, labeled with the apps that popularized them. LaunchBuddy screens use our own product photography. Treat this as a pattern library for indie developers, not a screenshot dump.',
  },
  {
    question: 'How accurate are the MRR bands?',
    answer:
      'They are rough public bands from indie posts, interviews, and store signals — not verified revenue. Use them to browse “tiny vs breakout,” not as financial research.',
  },
  {
    question: 'Can I submit a screen?',
    answer:
      'Not yet. If you ship an indie app with a screen you are proud of, ping @LaunchBuddy_App. The first catalog is curated on purpose so the filters stay meaningful.',
  },
  {
    question: 'Why does LaunchBuddy host this?',
    answer:
      'Indie developers copy the App Store’s average. Looking at a few sharp screens — paywalls, empty states, Watch glances — is a faster way to raise the floor before you submit.',
  },
] as const;

export function getScreenBySlug(slug: string): ScreenEntry | undefined {
  return SCREENS.find((screen) => screen.slug === slug);
}

export function getRelatedScreens(screen: ScreenEntry, limit = 3): ScreenEntry[] {
  const scored = SCREENS.filter((candidate) => candidate.slug !== screen.slug)
    .map((candidate) => {
      let score = 0;
      if (candidate.app === screen.app) score += 5;
      if (candidate.screenType === screen.screenType) score += 3;
      if (candidate.category === screen.category) score += 2;
      if (candidate.device === screen.device) score += 1;
      return { candidate, score };
    })
    .sort((a, b) => b.score - a.score);

  return scored.slice(0, limit).map((entry) => entry.candidate);
}

export function uniqueAppsCount(screens: ScreenEntry[] = SCREENS): number {
  return new Set(screens.map((screen) => screen.app)).size;
}

export function searchBlob(screen: ScreenEntry): string {
  return [screen.app, screen.title, screen.description, screen.category, screen.screenType, screen.device]
    .join(' ')
    .toLowerCase();
}
